[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
# wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
anyhow = "1"
yew-router = "0.16"
console_error_panic_hook = "0.1"
# gloo-net = "0.2.0"
log = "0.4"
# wasm-bindgen-futures = "0.4.30"
wasm-logger = "0.2"
