[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
anyhow = "1.0"
actix-web ="4"
actix-http = "3"
actix-cors ="0.6"
actix-service = "2"
actix-rt = "2"
serde = "1"
serde_json = "1"
dotenv = "0.15"
log = "0.4"
env_logger = "0.9"
diesel = { version = "1.4", features = ["postgres", "r2d2", "uuid", "chrono"] }